name: dart_cli_weather_forecast
description: A simple command-line weather application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '^3.5.0'

dependencies:
  http: 1.2.2
  dotenv: ^4.2.0

dev_dependencies:
  lint: ^2.0.0

assets:
  api-key.env